languageCode = "en"
languageName = "English"
weight = 1
title = "Jordi Viader Guerrero"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Jordi's personal website"

[params.author]
  name = "Jordi Viader Guerrero"
  email = "j.viaderguerrero@tudelft.nl; jordi@networkcultures.org"
  headline = ""
  bio = "Jordi Viader Guerrero (he/him) is a practice-based researcher working across philosophy of technology, media theory, science and technology studies and design research."
  links = [
    { email = "mailto:jordi@networkcultures.org" },
  ]
  image = "" 